package Financial;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import Financial.FinancialUnit;
import Financial.MyCodes.DbConnect;
import Financial.MyCodes.Methods;
import static com.sun.xml.internal.fastinfoset.alphabet.BuiltInRestrictedAlphabets.table;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.Format;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Vindula
 */
public class TableLoadFrame extends javax.swing.JFrame {

    /**
     * Creates new form TableLoad1
     */
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null, rs2 = null;
    String selected;
    String sqlDinin = "";
    public static int frameType = -1;
    
    final String sqlSellCat = "SELECT `orderid` as 'Order ID', `datecreated` as 'Date',"
            + " `total` as 'Total' FROM `cateringorder`";
    
    final String sqlSellEv = "SELECT `funid` as 'Function Id', `cusid` as 'Customer Id', `hallno` as 'Hall No',"
            + " `advanceamount` as 'Advance', `balancerent` as 'Balance' "
            + "FROM `function_payment`";
    
    final String sqlSellDin = "SELECT `order_ID` as 'Order Id',"
            + " `order_Time` as 'Timestamp', `price` as 'Value' "
            + "FROM `order_details`";

    
    public TableLoadFrame() {
        initComponents();
        selected = table.getSelectedItem().toString();
        frameType = FinancialUnit.passingValue;
        con = DbConnect.connect();
        sucessful.setEnabled(false);

        if(frameType == 5)
        {
 
            tableLoad(sqlSellCat);
            setTitle("Catering Orders");

        }
  
    }
    
        
    public void tableLoad(String sql)
    {
        try
        {
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            
        }catch(Exception e){
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        searchBox = new javax.swing.JTextField();
        sucessful = new javax.swing.JButton();
        table = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTable1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTable1FocusLost(evt);
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        searchBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        searchBox.setText("Search...");
        searchBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchBoxFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchBoxFocusLost(evt);
            }
        });
        searchBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBoxActionPerformed(evt);
            }
        });
        searchBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchBoxKeyReleased(evt);
            }
        });

        sucessful.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sucessful.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/like 2.png"))); // NOI18N
        sucessful.setText("Sucessful");
        sucessful.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sucessfulActionPerformed(evt);
            }
        });

        table.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        table.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Catering", "Dining", "Event Fees" }));
        table.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tableItemStateChanged(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("In");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1290, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(searchBox, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addGap(10, 10, 10)
                        .addComponent(table, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(sucessful, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchBox, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(table, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sucessful, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBoxActionPerformed

    private void tableItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tableItemStateChanged

        if("Catering".equals(table.getSelectedItem().toString()))
        {
            setTitle("Catering");
            frameType = 5;
            tableLoad(sqlSellCat);
            searchBox.setText("Search in order Id...");
            sucessful.setEnabled(false);
//            showSelected.setEnabled(true);
//            showSelected1.setEnabled(true);
        }
        else if("Dining".equals(table.getSelectedItem().toString()))
        {
            setTitle("Dining");
            frameType = 6;
            tableLoad(sqlSellDin);
            searchBox.setText("Search in order Id...");
            sucessful.setEnabled(false);
//            showSelected.setEnabled(true);
//            showSelected1.setEnabled(true);
        }
        else if("Event Fees".equals(table.getSelectedItem().toString()))
        {
            setTitle("Event Fees");
            frameType = 7;
            tableLoad(sqlSellEv);
            searchBox.setText("Search in function Id...");
            sucessful.setEnabled(false);
//            showSelected.setEnabled(false);
//            showSelected1.setEnabled(false);
            
        }
        else
        {
            
        }
        
    }//GEN-LAST:event_tableItemStateChanged

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        
       // delete.setEnabled(true);
        if(frameType == 7)
        {
            sucessful.setEnabled(true);
        }      
    }//GEN-LAST:event_jTable1MouseClicked

    private void searchBoxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchBoxFocusLost
        
        searchBox.setText("Search...");
       // showAll.doClick();
    }//GEN-LAST:event_searchBoxFocusLost

    private void searchBoxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchBoxFocusGained
       
         searchBox.setText("");
    }//GEN-LAST:event_searchBoxFocusGained

    private void jTable1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable1FocusLost
        // TODO add your handling code here:
       //sucessful.setEnabled(false);
    }//GEN-LAST:event_jTable1FocusLost

    private void searchBoxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchBoxKeyReleased
        // TODO add your handling code here:
        
        String searchText = searchBox.getText();
        sucessful.setEnabled(false);
        
        try
        {
            if(frameType == 5)
            {
                String sqlSearchCat = "SELECT `orderid` as 'Order ID', `datecreated` as 'Date',"
                + " `total` as 'Total' FROM `cateringorder` WHERE `orderid` LIKE '"+searchText+"%'";
                
                tableLoad(sqlSearchCat);
            }
            if(frameType == 6)
            {
                String sqlSearchDin = "SELECT `order_ID` as 'Order Id',"
            + " `order_Time` as 'Timestamp', `price` as 'Value' "
            + "FROM `order_details` WHERE `order_ID` LIKE '"+searchText+"%'";
                
                tableLoad(sqlSearchDin);
            }
            if(frameType == 7)
            {
                String sqlSearchEv = "SELECT `funid` as 'Function Id', `cusid` as 'Customer Id', `hallno` as 'Hall No',"
            + " `advanceamount` as 'Advance', `balancerent` as 'Balance' "
            + "FROM `function_payment`WHERE `funid` LIKE '"+searchText+"%'";
                
                tableLoad(sqlSearchEv);
            }
        }catch(Exception e)
        {
            System.out.println("Search error");
        }
        
    }//GEN-LAST:event_searchBoxKeyReleased

    private void jTable1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1FocusGained

    private void sucessfulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sucessfulActionPerformed
        // TODO add your handling code here:
        int r = -1;
        int recId = -1;
            try // Check if it is selected or not
            {
                r = jTable1.getSelectedRow();
                recId = (int)jTable1.getValueAt(r, 0);//get selected function id
            }catch(Exception e)
            {
                System.out.println("not selected");
            }
            
            String sqlUpdateEv = "UPDATE `function_payment` SET `balancerent`=0 "
                    + "WHERE `funid`='"+recId+"'";
        
            try
               {
                   pst = con.prepareStatement(sqlUpdateEv);
                   pst.execute();
                   tableLoad(sqlSellEv);
               }catch(Exception e){
                    System.out.println("not updated");
               }
            
            sucessful.setEnabled(false);
    }//GEN-LAST:event_sucessfulActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TableLoadFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TableLoadFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TableLoadFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TableLoadFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TableLoadFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField searchBox;
    private javax.swing.JButton sucessful;
    private javax.swing.JComboBox table;
    // End of variables declaration//GEN-END:variables
}
