package Delivery;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Rectangle;

import com.itextpdf.text.pdf.PRTokeniser;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import net.proteanit.sql.DbUtils;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author SUJITH
 */
public class Delivery_02 extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    String Order_ID = "";
    String Customer_Phone_Number = "";
    String Customer_Adress = "";
    String Driver_ID = "";
    String driver_name = "";
    String driver_phone = "";
    //  String Registration_Number = "";
    String Vehicle_Type = "";
    String Vehicle_ID = "";

    /**
     * Creates new form Delivery_02
     */
    public Delivery_02() {
        initComponents();
        conn = Dbconnecter.con();
        loadvehicle();

        loadDriver();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane6 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea1_request = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3_Assign_Driver = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2_SelectOrder = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1_Assign_Vehicle = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jTextField2_Charges1 = new javax.swing.JTextField();
        jButton1_CAL1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4_Chages = new javax.swing.JTable();
        jComboBox1_select_type = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jButton_Vehicle_id = new javax.swing.JButton();
        jButton_Driver_ID = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton_report = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jTextArea1_request.setColumns(20);
        jTextArea1_request.setRows(5);
        jScrollPane5.setViewportView(jTextArea1_request);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTable3_Assign_Driver.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Driver ID", "Name", "Phone"
            }
        ));
        jTable3_Assign_Driver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3_Assign_DriverMouseClicked(evt);
            }
        });
        jTable3_Assign_Driver.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable3_Assign_DriverKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3_Assign_Driver);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("Assign Driver ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTable2_SelectOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Order ID", "Customer Phone Number", "Customer Address"
            }
        ));
        jTable2_SelectOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2_SelectOrderMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2_SelectOrder);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("Select Event Order ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(36, 36, 36))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTable1_Assign_Vehicle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Vehicle Type", "Vehicle ID"
            }
        ));
        jTable1_Assign_Vehicle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1_Assign_VehicleMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTable1_Assign_VehicleMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1_Assign_Vehicle);
        if (jTable1_Assign_Vehicle.getColumnModel().getColumnCount() > 0) {
            jTable1_Assign_Vehicle.getColumnModel().getColumn(1).setHeaderValue("Vehicle ID");
        }

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("Assign Vehicle ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextField2_Charges1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2_Charges1ActionPerformed(evt);
            }
        });

        jButton1_CAL1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1_CAL1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1_CAL1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Delivery/icon/calcilate.png"))); // NOI18N
        jButton1_CAL1.setText("CAL");
        jButton1_CAL1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_CAL1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setText("Charges Rs");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setText("Order ID");

        jLabel11.setText("     Total price *5%");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField2_Charges1))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jButton1_CAL1))
                .addGap(20, 20, 20))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2_Charges1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1_CAL1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jLabel11))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTable4_Chages.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Order ID", "Customer Phone Number", "Vehicle ID", "Vehicle Type", "Driver ID", "Name", "Driver Phone Number", "Charges"
            }
        ));
        jScrollPane4.setViewportView(jTable4_Chages);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 881, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jComboBox1_select_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Type", "Event Order", "Buyer Order" }));
        jComboBox1_select_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1_select_typeActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jComboBox1_select_type, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(jButton1))
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 67, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jComboBox1_select_type, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(39, 39, 39)))
                                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Charts"));
        jPanel7.setToolTipText("");

        jButton_Vehicle_id.setBackground(new java.awt.Color(153, 204, 255));
        jButton_Vehicle_id.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_Vehicle_id.setText("Vehicle ID");
        jButton_Vehicle_id.setToolTipText("Update food details");
        jButton_Vehicle_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Vehicle_idActionPerformed(evt);
            }
        });

        jButton_Driver_ID.setBackground(new java.awt.Color(153, 204, 255));
        jButton_Driver_ID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_Driver_ID.setText("Driver ID");
        jButton_Driver_ID.setToolTipText("Update food details");
        jButton_Driver_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Driver_IDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_Driver_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Vehicle_id, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jButton_Vehicle_id, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_Driver_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Reports"));

        jButton_report.setBackground(new java.awt.Color(153, 204, 255));
        jButton_report.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_report.setText("Reports");
        jButton_report.setToolTipText("Update food details");
        jButton_report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_reportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jButton_report, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jButton_report, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1_CAL1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_CAL1ActionPerformed
        // TODO add your handling code here:
        double payment1;
        double charge;
        Order_ID = jLabel12.getText();
        if (jComboBox1_select_type.getSelectedItem() == "Event Order") {

            try {

                String sql = "select total from cateringorder where orderid = '" + Order_ID + "' ";
                pst = conn.prepareStatement(sql);
                rs = pst.executeQuery();
                if (rs.next()) {
                    payment1 = rs.getDouble(1);
                    charge = payment1 * 0.05;
                    jTextField2_Charges1.setText(("" + charge));

                }

            } catch (SQLException e) {

                //  System.out.println(e);
                common_methods_.errorMsg();
            }
        } else if (jComboBox1_select_type.getSelectedItem() == "Buyer Order");
        {
            String sql1 = "select pay from buyer_product where order_id = '" + Order_ID + "' ";
            try {
                pst = conn.prepareStatement(sql1);
                rs = pst.executeQuery();
                if (rs.next()) {
                    payment1 = rs.getDouble(1);
                    charge = payment1 * 0.05;
                    jTextField2_Charges1.setText(("" + charge));

                }

            } catch (SQLException e) {

                //  System.out.println(e);
                common_methods_.errorMsg();
            }

        }
    }//GEN-LAST:event_jButton1_CAL1ActionPerformed

    private void jTextField2_Charges1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2_Charges1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2_Charges1ActionPerformed

    private void jTable1_Assign_VehicleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1_Assign_VehicleMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1_Assign_VehicleMouseEntered

    private void jTable1_Assign_VehicleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1_Assign_VehicleMouseClicked
        // TODO add your handling code here:
        Order_ID = jLabel12.getText();
        int row = jTable1_Assign_Vehicle.getSelectedRow();

        Vehicle_ID = jTable1_Assign_Vehicle.getValueAt(row, 1).toString();
        Vehicle_Type = jTable1_Assign_Vehicle.getValueAt(row, 0).toString();

    }//GEN-LAST:event_jTable1_Assign_VehicleMouseClicked

    private void jTable2_SelectOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2_SelectOrderMouseClicked
        // TODO add your handling code here:
        //   loadOrder();
        if (jComboBox1_select_type.getSelectedItem() == "Event Order") {
            int row = jTable2_SelectOrder.getSelectedRow();

            Order_ID = jTable2_SelectOrder.getValueAt(row, 0).toString();
            Customer_Phone_Number = jTable2_SelectOrder.getValueAt(row, 1).toString();
            Customer_Adress = jTable2_SelectOrder.getValueAt(row, 2).toString();
            jLabel12.setText("" + Order_ID);

            load_order_info();
        } else if (jComboBox1_select_type.getSelectedItem() == "Buyer Order") {
            int row = jTable2_SelectOrder.getSelectedRow();

            Order_ID = jTable2_SelectOrder.getValueAt(row, 0).toString();
            Customer_Phone_Number = jTable2_SelectOrder.getValueAt(row, 1).toString();
            Customer_Adress = jTable2_SelectOrder.getValueAt(row, 2).toString();
            jLabel12.setText("" + Order_ID);

        }

    }//GEN-LAST:event_jTable2_SelectOrderMouseClicked

    private void jTable3_Assign_DriverKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable3_Assign_DriverKeyPressed

    }//GEN-LAST:event_jTable3_Assign_DriverKeyPressed

    private void jComboBox1_select_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1_select_typeActionPerformed
        // TODO add your handling code here:
        if (jComboBox1_select_type.getSelectedItem() == "Event Order") {
            loadOrder();
        } else if (jComboBox1_select_type.getSelectedItem() == "Buyer Order") {
            loadBuyersOrders();
        }
    }//GEN-LAST:event_jComboBox1_select_typeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        bill_delivery();
//insert deatils into charges table
        String a = jTextField2_Charges1.getText();

        String q = "INSERT INTO `delivery_chages`(`Order_ID`, `Customer_Phone_Number`, `customer_address`,`Vehicle_ID`,`Vehicle_Type`,`Driver_ID`,`Name`,`Driver_Phone _Number`,`charges`) VALUES('" + Order_ID + "','" + Customer_Phone_Number + "','" + Customer_Adress + "','" + Vehicle_ID + "','" + Vehicle_Type + "','" + Driver_ID + "','" + driver_name + "','" + driver_phone + "','" + a + "')";

        try {
            pst = conn.prepareStatement(q);
            pst.execute();
            loadChargesTable();

        } catch (SQLException e) {
            System.out.println(e);
            // errorMsg();

        }
        String s = "Not Free";
        //change driver status to not free
        String sql = "UPDATE staff SET 	status = '" + s + "' WHERE SID = '" + Driver_ID + "' ";

        //Insert to requests
        int Oid = Integer.parseInt(jTable2_SelectOrder.getValueAt(jTable2_SelectOrder.getSelectedRow(), 0).toString());
        String address = jTable2_SelectOrder.getValueAt(jTable2_SelectOrder.getSelectedRow(), 2).toString();
        String Oinfo = jComboBox1_select_type.getSelectedItem().toString();
        String sql9 = "INSERT INTO `request`(`OID`,`StaffPos`,workplace, OrderInfo) VALUES('" + Oid + "','Driver','" + address + "','" + Oinfo + "' )";
        try {
            pst = conn.prepareStatement(sql);
            pst.execute();
            loadDriver();
            pst = conn.prepareStatement(sql9);
            pst.execute();
        } catch (SQLException e) {
            //  System.out.println(e);
            common_methods_.errorMsg();
        }
//change vehicle status to not free
        String d = (Vehicle_ID);

        String sql1 = "UPDATE  vehicle SET Status = '" + s + "' WHERE Vehicle_ID = '" + d + "' ";
        try {
            pst = conn.prepareStatement(sql1);
            pst.execute();
            loadvehicle();

        } catch (SQLException e) {
            common_methods_.errorMsg();
            //  System.out.println(e);
        }

        if (jComboBox1_select_type.getSelectedItem() == "Event Order") {
            //update cateringorder table delivered
            String c = "Delivered";
            int oid = Integer.parseInt(Order_ID);

            String sql2 = "UPDATE  cateringorder SET delivered = '" + c + "' WHERE orderid = '" + oid + "' ";

            try {
                pst = conn.prepareStatement(sql2);
                pst.execute();
                loadOrder();
            } catch (SQLException e) {
                common_methods_.errorMsg();

            }

        } else if (jComboBox1_select_type.getSelectedItem() == "Buyer Order") {

            //update buyerorder table delivered
            String bc = "Delivered";
            int oidb = Integer.parseInt(Order_ID);

            String sql2 = "UPDATE  buyer_product SET delivered = '" + bc + "' WHERE order_id = '" + oidb + "' ";
            try {
                pst = conn.prepareStatement(sql2);
                pst.execute();
                loadBuyersOrders();

            } catch (SQLException e) {
                common_methods_.errorMsg();

            }

        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable3_Assign_DriverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3_Assign_DriverMouseClicked
        // TODO add your handling code here:
        Order_ID = jLabel12.getText();
        int row = jTable3_Assign_Driver.getSelectedRow();

        Driver_ID = jTable3_Assign_Driver.getValueAt(row, 0).toString();
        driver_name = jTable3_Assign_Driver.getValueAt(row, 1).toString();
        driver_phone = jTable3_Assign_Driver.getValueAt(row, 2).toString();


    }//GEN-LAST:event_jTable3_Assign_DriverMouseClicked

    private void jButton_Vehicle_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Vehicle_idActionPerformed
        // TODO add your handling code here:
        graph_Vehicle_ID();
    }//GEN-LAST:event_jButton_Vehicle_idActionPerformed

    private void jButton_Driver_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Driver_IDActionPerformed
        // TODO add your handling code here:
        graph_Driver_ID();
    }//GEN-LAST:event_jButton_Driver_IDActionPerformed

    private void jButton_reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_reportActionPerformed
        // TODO add your handling code here:
        report();
    }//GEN-LAST:event_jButton_reportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Delivery_02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Delivery_02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Delivery_02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Delivery_02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Delivery_02().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton1_CAL1;
    private javax.swing.JButton jButton_Driver_ID;
    private javax.swing.JButton jButton_Vehicle_id;
    private javax.swing.JButton jButton_report;
    private javax.swing.JComboBox<String> jComboBox1_select_type;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable1_Assign_Vehicle;
    private javax.swing.JTable jTable2_SelectOrder;
    private javax.swing.JTable jTable3_Assign_Driver;
    private javax.swing.JTable jTable4_Chages;
    private javax.swing.JTextArea jTextArea1_request;
    private javax.swing.JTextField jTextField2_Charges1;
    // End of variables declaration//GEN-END:variables

    private void loadvehicle() {
        String s = "Free";
        try {
            String sql = "SELECT Type,Vehicle_ID FROM vehicle WHERE Status= '" + s + "'";
            //+ "AND Vehicle_ID NOT IN (SELECT Registration_Number FROM delivery_chages)";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();

            jTable1_Assign_Vehicle.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException e) {
            //   System.out.println(e);
            common_methods_.errorMsg();

        }

    }

    private void loadOrder() {
        Date date = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-YYYY");
        String createdate = sdf.format(date);
        String d = "pending..";
        try {
            String sql = "SELECT orderid,phone,deliveryaddress FROM cateringorder where eventdate='" + createdate + "' AND  delivered ='" + d + "'";

            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();

            jTable2_SelectOrder.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException e) {
//            System.out.println(e);
            common_methods_.errorMsg();

        }
    }

    private void loadDriver() {

        try {
            String d = "Driver";
            // String s="working";
            String s = "Free";
            //String sql = "SELECT SID,Name,Phone FROM satff where satffpos='"+d+"' ";
            String sql = "SELECT SID,Name,Phone FROM staff where StaffPos ='" + d + "'AND status ='" + s + "'";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();

            jTable3_Assign_Driver.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException e) {
//            System.out.println(e);
            common_methods_.errorMsg();

        }
    }

    private void loadBuyersOrders() {
        String d = "Not Delivered";

        try {

            String sql = "SELECT order_id,phone, Address FROM buyers b , buyer_product bp WHERE b.Buyer_ID=bp.Buyer_ID and bp.delivered= '" + d + "' ";
            // + " b inner join buyer_product bp on  b.Buyer_ID = bp.Buyer_ID  ";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();

            jTable2_SelectOrder.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException e) {
            System.out.println(e);
            common_methods_.errorMsg();

        }
    }

    private void loadChargesTable() {
        try {
            String sql = "SELECT * FROM `delivery_chages`";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();

            jTable4_Chages.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException e) {
            //    System.o erut.println(e);
            common_methods_.errorMsg();

        }
    }

//    private void errorMsg() {
//        final JPanel panel = new JPanel();
//
//        JOptionPane.showMessageDialog(panel, "Warning!!! Something in Wrong. ", "KOGA restaurant",
//                JOptionPane.WARNING_MESSAGE);
//    }
    private void load_order_info() {
        int row = jTable2_SelectOrder.getSelectedRow();
// change
        Order_ID = jTable2_SelectOrder.getValueAt(row, 0).toString();
        
        try {
            String sql = "SELECT  OrderInfo from request where OID='" + Order_ID + "'";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            String s="";
            if(rs.next()){
            s=rs.getString(1);
            jTextArea1_request.setText(s);
            }
            //    jTable2_SelectOrder.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException e) {
            
            common_methods_.errorMsg();

        }
    }

    private void graph_Driver_ID() {
        int sr;
        String Type;
        sr = jTable4_Chages.getRowCount();

        DefaultPieDataset dataset = new DefaultPieDataset();

        for (int i = 0; i < sr; i++) {

            Type = jTable4_Chages.getValueAt(i, 6).toString();

            int count = 0;
            for (int j = 0; j < sr; j++) {
                if (jTable4_Chages.getValueAt(j, 6).toString().equals(Type)) {
                    count++;
                }

            }

            System.out.println(count);
            dataset.setValue("'" + Type + "'", new Integer(count));
        }

        JFreeChart chart = ChartFactory.createPieChart("Drivers in delivery orders", dataset, true, true, true);

        ChartFrame yourFrame = new ChartFrame("Koga Foods", chart);

        yourFrame.setSize(600, 600);

        yourFrame.setVisible(true);

    }

    private void graph_Vehicle_ID() {
        int sr;
        String Type;
        sr = jTable4_Chages.getRowCount();

        DefaultPieDataset dataset = new DefaultPieDataset();

        for (int i = 0; i < sr; i++) {

            Type = jTable4_Chages.getValueAt(i, 4).toString();

            int count = 0;
            for (int j = 0; j < sr; j++) {
                if (jTable4_Chages.getValueAt(j, 4).toString().equals(Type)) {
                    count++;
                }

            }

            System.out.println(count);
            dataset.setValue("'" + Type + "'", new Integer(count));
        }

        JFreeChart chart = ChartFactory.createPieChart("Vehicles in delivery orders", dataset, true, true, true);

        ChartFrame yourFrame = new ChartFrame("Koga Foods", chart);

        yourFrame.setSize(600, 600);

        yourFrame.setVisible(true);

    }

    private void report() {
        try {
            int sr = jTable4_Chages.getRowCount();
            int cc = jTable4_Chages.getColumnCount();
            Document document = new Document();
            PdfWriter.getInstance(document, new FileOutputStream("Report of Charges.pdf"));
            document.open();

            document.add(new Paragraph(""));//Image title

            document.add(new Paragraph("Koga Foods", FontFactory.getFont(FontFactory.TIMES_BOLD, 18, Font.BOLD)));
            document.add(new Paragraph("No. 83/1", FontFactory.getFont(FontFactory.TIMES_ITALIC, 10, Font.NORMAL)));
            document.add(new Paragraph("Heenatikumbura,", FontFactory.getFont(FontFactory.TIMES_ITALIC, 10, Font.NORMAL)));
            document.add(new Paragraph("Thalangama North,", FontFactory.getFont(FontFactory.TIMES_ITALIC, 10, Font.NORMAL)));
            document.add(new Paragraph("Koswattha,", FontFactory.getFont(FontFactory.TIMES_ITALIC, 10, Font.NORMAL)));
            document.add(new Paragraph("0772342134,", FontFactory.getFont(FontFactory.TIMES_ITALIC, 10, Font.NORMAL)));

            document.add(new Paragraph(new Date().toString()));
            document.add(new Paragraph("---------------------------------------------------------------------------------"));
            PdfPTable table = new PdfPTable(cc);

            PdfPCell cell = new PdfPCell(new Paragraph("Details of Charges"));
            cell.setColspan(cc);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell.setBackgroundColor(BaseColor.GREEN);
            table.addCell(cell);
            for (int i = 0; i < jTable4_Chages.getColumnCount(); i++) {

                PdfPCell cellCol = new PdfPCell(new Paragraph(jTable4_Chages.getColumnName(i), FontFactory.getFont(FontFactory.TIMES_BOLD, 10, Font.BOLD)));
                cellCol.setColspan(1);
                cellCol.setHorizontalAlignment(Element.ALIGN_CENTER);

                table.addCell(cellCol);

            }
            if (sr > 0) {
                for (int i = 0; i < sr; i++) {

                    for (int j = 0; j < cc; j++) {
                        if (jTable4_Chages.getValueAt(i, j) != null) {
                            table.addCell(new Paragraph(jTable4_Chages.getValueAt(i, j).toString(), FontFactory.getFont(FontFactory.TIMES_BOLD, 8, Font.NORMAL)));
                        } else {
                            table.addCell(" ");
                        }
                    }

                }
            }

            document.add(table);
            document.close();
            JOptionPane.showMessageDialog(null, "Report Saved");

            try {

                Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler "
                        + "D:\\hotelandresturent\\hotelandresturent\\Report of Charges.pdf");

            } catch (Exception ex) {

                JOptionPane.showMessageDialog(null, ex);
            }

        } catch (Exception ex) {

            JOptionPane.showMessageDialog(null, ex);
        }
    }

    private void bill_delivery() {
        Order_ID = jLabel12.getText();
        int row = jTable3_Assign_Driver.getSelectedRow();

        Driver_ID = jTable3_Assign_Driver.getValueAt(row, 0).toString();
        driver_name = jTable3_Assign_Driver.getValueAt(row, 1).toString();
        driver_phone = jTable3_Assign_Driver.getValueAt(row, 2).toString();

        ////
        if (jComboBox1_select_type.getSelectedItem() == "Event Order") {
            int row1 = jTable2_SelectOrder.getSelectedRow();

            Customer_Phone_Number = jTable2_SelectOrder.getValueAt(row1, 1).toString();
            Customer_Adress = jTable2_SelectOrder.getValueAt(row1, 2).toString();
            jLabel12.setText("" + Order_ID);

        } else if (jComboBox1_select_type.getSelectedItem() == "Buyer Order") {
            int row2 = jTable2_SelectOrder.getSelectedRow();

            Customer_Phone_Number = jTable2_SelectOrder.getValueAt(row2, 1).toString();
            Customer_Adress = jTable2_SelectOrder.getValueAt(row2, 2).toString();
            jLabel12.setText("" + Order_ID);

        }
        //////
        Order_ID = jLabel12.getText();
        int row3 = jTable1_Assign_Vehicle.getSelectedRow();

        Vehicle_ID = jTable1_Assign_Vehicle.getValueAt(row3, 1).toString();
        Vehicle_Type = jTable1_Assign_Vehicle.getValueAt(row3, 0).toString();

        bill(Driver_ID, driver_name, driver_phone, Order_ID, Customer_Phone_Number, Customer_Adress, Vehicle_ID, Vehicle_Type);
    }

    private void bill(String Driver_ID, String driver_name, String driver_phone, String Order_ID, String Customer_Phone_Number, String Customer_Adress, String Vehicle_ID, String Vehicle_Type) {
        try {
            Document document = new Document();
            
            PdfWriter.getInstance(document, new FileOutputStream("Delivery Charges.pdf"));
            document.open();
                               
            document.add(new Paragraph(""));

            document.add(new Paragraph("Koga Foods", FontFactory.getFont(FontFactory.TIMES_BOLD, 18, Font.BOLD)));
            document.add(new Paragraph("No. 83/1", FontFactory.getFont(FontFactory.TIMES_ITALIC, 10, Font.NORMAL)));
            document.add(new Paragraph("Heenatikumbura,", FontFactory.getFont(FontFactory.TIMES_ITALIC, 10, Font.NORMAL)));
            document.add(new Paragraph("Thalangama North,", FontFactory.getFont(FontFactory.TIMES_ITALIC, 10, Font.NORMAL)));
            document.add(new Paragraph("Koswattha.", FontFactory.getFont(FontFactory.TIMES_ITALIC, 10, Font.NORMAL)));
            document.add(new Paragraph("0772342134", FontFactory.getFont(FontFactory.TIMES_ITALIC, 10, Font.NORMAL)));

            document.add(new Paragraph(new Date().toString()));
            document.add(new Paragraph("______________________________________________"));
            document.add(new Paragraph(""));                                                             
            document.add(new Paragraph("  Order ID : " + Order_ID + "", FontFactory.getFont(FontFactory.TIMES_ITALIC, 10, Font.NORMAL)));
            document.add(new Paragraph(""));
           document.add(new Paragraph("______________________________________________"));
             document.add(new Paragraph("-------Driver's Details-------", FontFactory.getFont(FontFactory.TIMES, 10, Font.NORMAL)));
            document.add(new Paragraph(""));
            document.add(new Paragraph("Driver Name :"+driver_name+"", FontFactory.getFont(FontFactory.TIMES, 10, Font.NORMAL)));
            document.add(new Paragraph("Driver ID :"+Driver_ID+"", FontFactory.getFont(FontFactory.TIMES, 10, Font.NORMAL)));
            document.add(new Paragraph("Phone Number of Driver :"+driver_phone+"", FontFactory.getFont(FontFactory.TIMES, 10, Font.NORMAL)));
              document.add(new Paragraph("Vehicle Registration Number ID :"+Vehicle_ID+"", FontFactory.getFont(FontFactory.TIMES, 10, Font.NORMAL)));
            document.add(new Paragraph("Type of Vehicle :"+Vehicle_Type+"", FontFactory.getFont(FontFactory.TIMES, 10, Font.NORMAL)));
          document.add(new Paragraph(""));
             document.add(new Paragraph("-------Customer's Details-------", FontFactory.getFont(FontFactory.TIMES, 10, Font.NORMAL)));
            document.add(new Paragraph(""));
            document.add(new Paragraph("Phone Number Of Customer :"+Customer_Phone_Number+"", FontFactory.getFont(FontFactory.TIMES, 10, Font.NORMAL)));
            document.add(new Paragraph("Address of Customer :"+Customer_Adress+"", FontFactory.getFont(FontFactory.TIMES, 10, Font.NORMAL)));
            document.add(new Paragraph(""));
             document.add(new Paragraph("-------Delivery Charges : Rs."+jTextField2_Charges1.getText(), FontFactory.getFont(FontFactory.TIMES, 10, Font.NORMAL)));
            document.add(new Paragraph(""));
             document.add(new Paragraph(""));
             document.add(new Paragraph("**  Thank You  ***", FontFactory.getFont(FontFactory.TIMES, 10, Font.NORMAL)));
            document.add(new Paragraph(""));
            //document.setPageSize(PageSize.A4    );
            document.close();            
       
            JOptionPane.showMessageDialog(null, "Report Saved");
            
             try {
//TAKE LINK
                Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler "
                        + "E:\\hotelandresturent\\Delivery Charges.pdf");

            } catch (Exception ex) {

                JOptionPane.showMessageDialog(null, ex);
            }

        } catch (Exception e) {

        }
    }

}
