/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import Financial.FinancialUnit;
import Inventory_codes.EquipmentsHandling;
import Inventory_codes.IngredientsHandling;
import Inventory_codes.Invoice;
import Inventory_codes.SuppliersHandling;
import StaffManagement.Attendance;
import StaffManagement.Report;
import StaffManagement.Resignation;
import StaffManagement.StaffRegistration;
import StaffManagement.AssignSalaryFactors;
import StaffManagement.TaskAssignment;
import StaffManagement.salaryReport;
import java.beans.PropertyVetoException;
import javax.swing.JOptionPane;
import maintance_codes.Maintance1;

/**
 *
 * @author Vindula
 */
public class Business extends javax.swing.JInternalFrame {

    /**
     * Creates new form business
     */
    public Business() {
        ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);
        initComponents();
        financial.doClick();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        financial = new javax.swing.JButton();
        maintenance = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        backupDb = new javax.swing.JButton();
        importDb = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        financial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        financial.setText("Financial Management");
        financial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                financialActionPerformed(evt);
            }
        });

        maintenance.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        maintenance.setText("Maintenance");
        maintenance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maintenanceActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("The Business");

        backupDb.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        backupDb.setText("Backup Database");

        importDb.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        importDb.setText("Import Database");

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 638, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Inventory and Supply", "Equipments Handling", "Ingredients Handling", "Suppliers Handling", "Invoice" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Staff", "Staff Registration", "Staff Resignation", "Attendance", "Staff Salary Report", "Task Assignment", "Salary Factor Assignment", "Generate Staff Report" }));
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });
        jComboBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox2MouseClicked(evt);
            }
        });
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.TRAILING, 0, 0, Short.MAX_VALUE)
                        .addComponent(financial, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                        .addComponent(maintenance, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                        .addComponent(backupDb, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                        .addComponent(importDb, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jDesktopPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(financial, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(maintenance, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(backupDb, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(importDb, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 30, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void financialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_financialActionPerformed
        FinancialUnit b1 = new FinancialUnit();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(b1);
        b1.setLocation(0, 0);
        b1.setVisible(true);
        try 
        {
            b1.setMaximum(true);
        } 
        catch (PropertyVetoException e)
        {
            JOptionPane.showMessageDialog(null, "Maximaize error", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_financialActionPerformed

    private void maintenanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maintenanceActionPerformed
        Maintance1 m1=new Maintance1();
         jDesktopPane1.removeAll();
        jDesktopPane1.add(m1);
        m1.setLocation(0, 0);
        m1.setVisible(true);
        try 
        {
            m1.setMaximum(true);
        } 
        catch (PropertyVetoException e)
        {
            JOptionPane.showMessageDialog(null, "Maximaize error", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_maintenanceActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String selecteditem=jComboBox1.getSelectedItem().toString();
        switch(selecteditem){
            case("Equipments Handling"):
                 EquipmentsHandling ll = new EquipmentsHandling();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(ll).setVisible(true);
        ll.setLocation(0,0);
          try {
            ll.setMaximum(true);
        } catch (PropertyVetoException ex) {
           
            JOptionPane.showMessageDialog(null, "Maximize Error" + ex.getLocalizedMessage(), "ERROR",
                                    JOptionPane.ERROR_MESSAGE);//Message Box Displays for exception,
        }
         break; 
         case("Ingredients Handling") :
             IngredientsHandling l2 = new IngredientsHandling();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(l2).setVisible(true);
        l2.setLocation(0,0);
          try {
            l2.setMaximum(true);
        } catch (PropertyVetoException ex) {
           
            JOptionPane.showMessageDialog(null, "Maximize Error" + ex.getLocalizedMessage(), "ERROR",
                                    JOptionPane.ERROR_MESSAGE);//Message Box Displays for exception,
        }
          break;
          case("Suppliers Handling"):
               SuppliersHandling l3 = new SuppliersHandling();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(l3).setVisible(true);
        l3.setLocation(0,0);
          try {
            l3.setMaximum(true);
        } catch (PropertyVetoException ex) {
           
            JOptionPane.showMessageDialog(null, "Maximize Error" + ex.getLocalizedMessage(), "ERROR",
                                    JOptionPane.ERROR_MESSAGE);//Message Box Displays for exception,
        }
         break;
         case("Invoice"):
             Invoice l4 = new Invoice();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(l4).setVisible(true);
        l4.setLocation(0,0);
          try {
            l4.setMaximum(true);
        } catch (PropertyVetoException ex) {
           
            JOptionPane.showMessageDialog(null, "Maximize Error" + ex.getLocalizedMessage(), "ERROR",
                                    JOptionPane.ERROR_MESSAGE);//Message Box Displays for exception,
        }
        break;
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
//        String selecteditem2=jComboBox2.getSelectedItem().toString();
//        switch(selecteditem2){
//            case("Staff Registration"):
//                StaffRegistration R1 = new StaffRegistration();
//            jDesktopPane1.removeAll();
//            jDesktopPane1.add(R1).setVisible(true);
//            R1.setLocation(0, 0);
////            R1.pack();
//            try
//            {
//                R1.setMaximum(true);
//            }
//            catch (PropertyVetoException e)
//            {
//                JOptionPane.showMessageDialog(null,e.getLocalizedMessage() + " >Maximize Error", "Error", JOptionPane.ERROR_MESSAGE);
//            } 
//            break;
//            case("Attendance"):
//                
//        }
        if(jComboBox2.getSelectedIndex()==1){
            

            StaffRegistration R1 = new StaffRegistration();
            jDesktopPane1.removeAll();
            jDesktopPane1.add(R1).setVisible(true);
            R1.setLocation(0, 0);
            R1.pack();
            try
            {
                R1.setMaximum(true);
            }
            catch (PropertyVetoException e)
            {
                JOptionPane.showMessageDialog(null,e.getLocalizedMessage() + " >Maximize Error", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }

        else if(jComboBox2.getSelectedIndex()==2){
            jDesktopPane1.removeAll();
            Resignation rs1 = new Resignation();
            jDesktopPane1.add(rs1);
            rs1.setLocation(0, 0);
            rs1.setVisible(true);
            try
            {
                rs1.setMaximum(true);

            }
            catch(PropertyVetoException e)
            {
                JOptionPane.showMessageDialog(null,e.getLocalizedMessage() + " >Maximize Error", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }

        else if(jComboBox2.getSelectedIndex()==3){
            jDesktopPane1.removeAll();
            Attendance rs1 = new Attendance();
            jDesktopPane1.add(rs1).setVisible(true);
            rs1.setLocation(0, 0);

            try
            {
                rs1.setMaximum(true);
            }
            catch (PropertyVetoException e)
            {
                JOptionPane.showMessageDialog(null,e.getLocalizedMessage() + " >Maximize Error", "Error", JOptionPane.ERROR_MESSAGE);
            }

        }

        else if(jComboBox2.getSelectedIndex()==4){
            jDesktopPane1.removeAll();
            salaryReport sr1 = new salaryReport();
            jDesktopPane1.add(sr1);
            sr1.setLocation(0, 0);
            sr1.setVisible(true);
            try {
                sr1.setMaximum(true);
            } catch (PropertyVetoException e) {
                JOptionPane.showMessageDialog(null,e.getLocalizedMessage() + " >Maximize Error", "Error", JOptionPane.ERROR_MESSAGE);
            }

        }

        else if(jComboBox2.getSelectedIndex()==5){
            jDesktopPane1.removeAll();
            TaskAssignment ta1 =new TaskAssignment();
            jDesktopPane1.add(ta1);
            ta1.setLocation(0, 0);
            ta1.setVisible(true);
            try{
                ta1.setMaximum(true);

            }catch(PropertyVetoException e){
                JOptionPane.showMessageDialog(null,e.getLocalizedMessage() + " >Maximize Error", "Error", JOptionPane.ERROR_MESSAGE);
            }

        }

        else if(jComboBox2.getSelectedIndex()==6){
            jDesktopPane1.removeAll();
            AssignSalaryFactors raf1 = new AssignSalaryFactors();
            jDesktopPane1.add(raf1);
            raf1.setLocation(0, 0);
            raf1.setVisible(true);
            try{
                raf1.setMaximum(true);

            }catch(PropertyVetoException e){
                JOptionPane.showMessageDialog(null,e.getLocalizedMessage() + " >Maximize Error", "Error", JOptionPane.ERROR_MESSAGE);
            }

        }

        else if(jComboBox2.getSelectedIndex()==7){
            jDesktopPane1.removeAll();
            Report r1 = new Report();
            jDesktopPane1.add(r1);
            r1.setLocation(0, 0);
            r1.setVisible(true);
            try {
                r1.setMaximum(true);
            } catch (PropertyVetoException e) {
                JOptionPane.showMessageDialog(null,e.getLocalizedMessage() + " >Maximize Error", "Error", JOptionPane.ERROR_MESSAGE);
            }

        }
        else
        jDesktopPane1.removeAll();

        jDesktopPane1.updateUI();
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void jComboBox2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox2MouseClicked

    }//GEN-LAST:event_jComboBox2MouseClicked

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backupDb;
    private javax.swing.JButton financial;
    private javax.swing.JButton importDb;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton maintenance;
    // End of variables declaration//GEN-END:variables
}
