/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import Delivery.DeliveryI_01;
import food.dinein12;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.beans.PropertyVetoException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Vindula
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
        business.doClick();
        
         this.addWindowListener(new WindowAdapter() {//Llstning for pressing close button
            @Override
            public void windowClosing(WindowEvent e) {
                //option box and taking a value from it 1,0
                int y = JOptionPane.showConfirmDialog(null, "Do you want yo exit?", "close", JOptionPane.YES_NO_OPTION);

                if(y == JOptionPane.YES_OPTION)
                   dispose();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPaneHome = new javax.swing.JDesktopPane();
        dining = new javax.swing.JButton();
        events = new javax.swing.JButton();
        delivery = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        business = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPaneHomeLayout = new javax.swing.GroupLayout(jDesktopPaneHome);
        jDesktopPaneHome.setLayout(jDesktopPaneHomeLayout);
        jDesktopPaneHomeLayout.setHorizontalGroup(
            jDesktopPaneHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPaneHomeLayout.setVerticalGroup(
            jDesktopPaneHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 301, Short.MAX_VALUE)
        );

        dining.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dining.setText("Dining");
        dining.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diningActionPerformed(evt);
            }
        });

        events.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        events.setText("Organize Events");
        events.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventsActionPerformed(evt);
            }
        });

        delivery.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        delivery.setText("Delivery");
        delivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deliveryActionPerformed(evt);
            }
        });

        logout.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        business.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        business.setText("Business");
        business.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                businessActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("Change Password");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dining, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(events, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(delivery, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(business, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 195, Short.MAX_VALUE))
                    .addComponent(jDesktopPaneHome))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dining, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(events, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delivery, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(business, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDesktopPaneHome)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void businessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_businessActionPerformed
        
        
        Business b1 = new Business();
        jDesktopPaneHome.removeAll();
        jDesktopPaneHome.add(b1);
        b1.setLocation(0, 0);
        b1.setVisible(true);
        try 
        {
            b1.setMaximum(true);
        } 
        catch (PropertyVetoException e)
        {
            JOptionPane.showMessageDialog(null, "Maximaize error", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_businessActionPerformed

    private void deliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deliveryActionPerformed
        // TODO add your handling code here:
        //Delivery_03
        DeliveryI_01 d1 = new DeliveryI_01();
        jDesktopPaneHome.removeAll();
        jDesktopPaneHome.add(d1);
        d1.setLocation(0, 0);
        d1.setVisible(true);
        try 
        {
            d1.setMaximum(true);
        } 
        catch (PropertyVetoException e)
        {
            JOptionPane.showMessageDialog(null, "Maximaize error", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_deliveryActionPerformed

    private void eventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventsActionPerformed
        //EventMain
        EventsCatering d1 = new EventsCatering();
        jDesktopPaneHome.removeAll();
        jDesktopPaneHome.add(d1);
        d1.setLocation(0, 0);
        d1.setVisible(true);
        try 
        {
            d1.setMaximum(true);
        } 
        catch (PropertyVetoException e)
        {
            JOptionPane.showMessageDialog(null, "Maximaize error", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_eventsActionPerformed

    private void diningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diningActionPerformed
        // TODO add your handling code here:
        dinein12 d2=new dinein12();
//        d1.setVisible(true);
        jDesktopPaneHome.removeAll();
        jDesktopPaneHome.add(d2);
        d2.setLocation(0, 0);
        d2.setVisible(true);
        try 
        {
            d2.setMaximum(true);
        } 
        catch (PropertyVetoException e)
        {
            JOptionPane.showMessageDialog(null, "Maximaize error", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_diningActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        
        Login mo = new Login();
        mo.setVisible(true);
        //mo.setExtendedState(mo.getExtendedState() | Home.MAXIMIZED_BOTH);
        this.dispose();
    }//GEN-LAST:event_logoutActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        ChangePassword mo = new ChangePassword();
       // mo.setLocation(WIDTH/2, HEIGHT/2);
        mo.setVisible(true);
        //mo.setExtendedState(mo.getExtendedState() | Home.MAXIMIZED_BOTH);
        this.dispose();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton business;
    private javax.swing.JButton delivery;
    private javax.swing.JButton dining;
    private javax.swing.JButton events;
    private javax.swing.JButton jButton3;
    private javax.swing.JDesktopPane jDesktopPaneHome;
    private javax.swing.JButton logout;
    // End of variables declaration//GEN-END:variables
}
